### ISSUE TITLE
[Feature] 자유게시판 화면 구현

### ISSUE THREAD

**Issue by ayz1070** [APP-Android2/FinalProject-ShoppingMallService-team5#6]
### 추가하려는 기능에 대해 간결하게 설명해주세요

자유게시판에 필요한 화면들 및 화면 간 전환 이벤트를 구현한다.

## 체크 리스트
- [x] 발행자 확인
- [x] 프로젝트 확인

**Comment by ayz1070** [comment]
![Screenshot_20240327_112041](https://github.com/APP-Android2/FinalProject-ShoppingMallService-team5/assets/80628496/180d655d-bee7-4e32-a89e-c24880ed8ace)

메인화면 디자인 피드백 바랍니다

**Comment by cny1213** [comment]
강아지가 귀엽네요

**Comment by chanho0908** [comment]
어느집 공주님인지 너무 귀여워요 ^_^

**Comment by chanho0908** [comment]
프로젝트 체크리스트 확인해주세요!
